Vagrant.configure("2") do |config|
  config.vm.define "web"  do |docker|
    docker.vm.network :private_network, type: "dhcp", docker_network__internal: true
    docker.vm.network :private_network, ip: "192.168.128.99", netmask: "24"
    docker.vm.provider "docker" do |d|
       d.image = "nginx"
       d.name = "app1"
       d.ports = ["8081:80"]
     end
     end
     config.vm.define "web2" do |config|
     config.vm.provider "docker" do |d|
       d.image = "wordpress"
       d.name = "app2"
       d.ports = ["8082:81"]
     end
     end
     config.vm.define "db" do |config|
       config.vm.provider "docker" do |d|
         d.image = "postgres"
         d.name = "db"
         d.ports = ["8083:5432"]
         d.env = {"POSTGRES_PASSWORD":"postgres"}
       end
       end
   end